import "../styles/globals.css";
import Layout from "../components/layout/layout";
import Head from "next/head";
import { ImageContextProvider } from "../store/imageContext.js";
import { ActiveContextProvider } from "../store/activeContext.js";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function App({ Component, pageProps }) {
  return (
    <ImageContextProvider>
      <ActiveContextProvider>
        <Layout>
          <Head>
            <meta
              name="viewport"
              content="width=device-width, intial-scale=1"
            />
          </Head>
          <Component {...pageProps} />
        </Layout>
      </ActiveContextProvider>
    </ImageContextProvider>
  );
}

export default App;
