import "../styles/globals.css";
import Layout from "../components/layout/layout";
import Head from "next/head";
import { ImageContextProvder } from "../store/imageContext.js";
import { Fragment } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function App({ Component, pageProps }) {
  return (
    <ImageContextProvder>
      <Layout>
        <Head>
          <meta name="viewport" content="width=device-width, intial-scale=1" />
        </Head>
        <Component {...pageProps} />
      </Layout>
    </ImageContextProvder>
  );
}

export default App;
